config/routes.rb
Rails.application.routes.draw do
  resources :companies do
    collection do
      get :search
      get :result
    end
    resources :matters do
      collection do
        get :search
      end
      resources :logs
    end
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :matters
    
    validates :name, presence: true
    validates :phone_number, presence: true, format: {with: /\A(((0(\d{1}[-(]?\d{4}|\d{2}[-(]?\d{3}|\d{3}[-(]?\d{2}|\d{4}[-(]?\d{1}|[5789]0[-(]?\d{4})[-)]?)|\d{1,4}\-?)\d{4}|0120[-(]?\d{3}[-)]?\d{3})\z/}
    validates :address, presence: true
    validates :industry, presence: true
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :matter
  belongs_to:user
  
  validates :next_approach_date, presence: true
  validates :status, presence: true
  validates :comment, presence: true
  
  enum status: {
    approach: 0,
    meeting: 1,
    abandonment: 2,
    close: 3
  },  _prefix: true
  
end

app/models/matter.rb
class Matter < ApplicationRecord
    belongs_to :company
    has_many :logs
    
    validates :name, presence: true
    validates :detail, presence: true
    validates :contact_person, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :logs, dependent: :destroy, foreign_key: :log_user_id
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :name, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    protected
    def configure_permitted_parameters
      # サインアップ時にnameのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      # アカウント編集の時にnameのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_search
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  def index
  end

  # GET /companies/1
  def show
    @q_matter = @company.matters.order(updated_at: "DESC").ransack(params[:q])
    @matters = @q_matter.result(distinct: true).page(params[:page])
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  def create
    @company = Company.new(company_params)

    if @company.save
      redirect_to @company, notice: '企業情報の作成に成功しました'
    else
      render :new
    end
  end

  # PATCH/PUT /companies/1
  def update
    if @company.update(company_params)
      redirect_to @company, notice: '企業情報の更新に成功しました'
    else
      render :edit
    end
  end

  # DELETE /companies/1
  def destroy
    begin
      @company.destroy
      redirect_to companies_url, notice: '企業情報を削除しました'
    rescue
      redirect_to companies_url, alert: '案件があるため削除に失敗しました'
    end
  end
  
  def search
  end

  def result
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find_by(id: params[:id])
      redirect_to(companies_url, alert: "ERROR!!") if @company.blank?
    end
    
    def set_search
      @q_company = Company.order(:id).ransack(params[:q])
      @companies = @q_company.result(distinct: true).page(params[:page])
    end

    # Only allow a trusted parameter "white list" through.
    def company_params
      params.require(:company).permit(:name, :phone_number, :address, :industry)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        redirect_to companies_path if user_signed_in?
    end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_company
  before_action :set_matter
  before_action :set_log, only: [:show, :edit, :update, :destroy]
  before_action :ensure_correct_user, only: [:edit,:update,:destroy]

  # GET /logs/new
  def new
    @log = @matter.logs.new
  end

  # GET /logs/1/edit
  def edit
  end

  # POST /logs
  def create
    @log = @matter.logs.new(log_params)

    if @log.save
      redirect_to company_matter_path(id: @matter.id), notice: 'ログの登録に成功しました'
    else
      render :new
    end
  end

  # PATCH/PUT /logs/1
  def update
    if @log.update(log_params)
      redirect_to company_matter_path(id: @matter.id), notice: 'ログの更新に成功しました'
    else
      render :edit
    end
  end

  # DELETE /logs/1
  def destroy
    @log.destroy
    redirect_to company_matter_path(id: @matter.id), notice: 'ログを削除しました'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    
    def set_company
      @company = Company.find_by(id: params[:company_id])
      redirect_to(company_url, alert: "ERROR!!") if @company.blank?
    end
    
    def set_matter
      @matter = @company.matters.find_by(id: params[:matter_id])
      redirect_to(company_matter_url, alert: "ERROR!!") if @matter.blank?
    end
    
    def set_log
      @log = @matter.logs.find_by(id: params[:id])
    end

    def log_params
      params.require(:log).permit(:next_approach_date, :status, :comment, :matter_id, :user_id)
    end
    
    def ensure_correct_user
      if @log.user_id != current_user.id
        flash[:alert] = "権限がありません"
        redirect_to company_matter_path(id: @matter.id)
      end
    end
end

app/controllers/matters_controller.rb
class MattersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_company
  before_action :set_search
  before_action :set_matter, only: [:show, :edit, :update, :destroy]

  # GET /matters
  def index
  end

  # GET /matters/1
  def show
    @q_log = @matter.logs.order(updated_at: "DESC").ransack(params[:q])
    @logs = @q_log.result(distinct: true).page(params[:page])
  end

  # GET /matters/new
  def new
    @matter = @company.matters.new
  end

  # GET /matters/1/edit
  def edit
  end

  # POST /matters
  def create
    @matter = @company.matters.new(matter_params)

    if @matter.save
      redirect_to company_path(id: @company.id), notice: '案件の作成に成功しました'
    else
      render :new
    end
  end

  # PATCH/PUT /matters/1
  def update
    if @matter.update(matter_params)
      redirect_to company_path(id: @company.id), notice: '案件の更新に成功しました'
    else
      render :edit
    end
  end

  # DELETE /matters/1
  def destroy
    begin 
      @matter.destroy
      redirect_to company_path(id: @company.id), notice: '案件を削除しました'
    rescue
      redirect_to company_path(id: @company.id), alert: 'ログがあるため削除に失敗しました'
    end
  end
  
  def search
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find_by(id: params[:company_id])
      redirect_to(company_url, alert: "ERROR!!") if @company.blank?
    end
    
    def set_matter
      @matter = @company.matters.find_by(id: params[:id])
    end
    
    def set_search
      @q_matter = @company.matters.order(updated_at: "DESC").ransack(params[:q])
      @matters = @q_matter.result(distinct: true).page(params[:page])
    end

    def matter_params
      params.require(:matter).permit(:name, :detail, :contact_person, :company_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def bs4_bgcolor_for(flash_key)
     case flash_key
     when "success"
       "alert-success"
     when "error"
       "alert-danger"
     when "alert"
       "alert-warning"
     when "notice"
       "alert-info"
     else
       flash_key.to_s
     end
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/matters_helper.rb
module MattersHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation" class="alert-danger">
      <h2><%= pluralize(company.errors.count, "error") %> 登録に失敗しました:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :industry %>
    <%= form.text_field :industry %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>企業情報編集</h1>

<%= render 'form', company: @company %>

<%= link_to '詳細画面へ戻る', @company %> |
<%= link_to '一覧へ戻る', companies_path %>

app/views/companies/index.html.erb
<h2>メニュー</h2>
<ul>
  <li><%= link_to '新規企業登録', new_company_path %></li>
  <li><%= link_to '会社情報検索', search_companies_path %></li>
</ul>

<br>
<h2>企業一覧</h2>
<div class="table-responsive-sm">
<table class="table table-bordered table-sm">
  <thead class="thead-light">
    <tr>
      <th scope="col"><%= sort_link(@q_company, :id, "企業コード") %></th>
      <th scope="col"><%= sort_link(@q_company, :name) %></th>
      <th scope="col"><%= sort_link(@q_company, :phone_number) %></th>
      <th scope="col"><%= sort_link(@q_company, :address) %></th>
      <th scope="col"><%= sort_link(@q_company, :industry) %></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td scope="row"><%= link_to format("%010d",company.id),company %></td>
        <td><%= company.name %></td>
        <td><%= company.phone_number %></td>
        <td><%= company.address %></td>
        <td><%= company.industry %></td>

        <td><%= link_to '編集', edit_company_path(company) %></td>
        <td><%= link_to '削除', company, method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<%= paginate @companies %>

app/views/companies/new.html.erb
<h1>新規企業登録</h1>

<%= render 'form', company: @company %>

<%= link_to '一覧へ戻る', companies_path %>

app/views/companies/result.html.erb
<h2>検索結果</h2>
<% if @companies.any? %>
<div class="table-responsive-sm">
<table class="table table-bordered table-sm">
  <thead class="thead-light">
    <tr>
      <th scope="col"><%= sort_link(@q_company, :id, "企業コード") %></th>
      <th scope="col"><%= sort_link(@q_company, :name) %></th>
      <th scope="col"><%= sort_link(@q_company, :phone_number) %></th>
      <th scope="col"><%= sort_link(@q_company, :address) %></th>
      <th scope="col"><%= sort_link(@q_company, :industry) %></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td scope="row"><%= link_to format("%010d",company.id),company %></td>
        <td><%= company.name %></td>
        <td><%= company.phone_number %></td>
        <td><%= company.address %></td>
        <td><%= company.industry %></td>

        <td><%= link_to '編集', edit_company_path(company) %></td>
        <td><%= link_to '削除', company, method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<% else %>
  <p class="text-danger"><%= '検索結果がありません。' %></p>
<% end %>
<%= paginate @companies %>
<br/>
<%= link_to '検索フォームに戻る', search_companies_path %>
<%= link_to '会社一覧へ戻る', companies_path %>

app/views/companies/search.html.erb
<h2>検索フォーム</h2>
<%= search_form_for @q_company,url:result_companies_path do |f| %>

  <div class="field">
    <%= f.label :id ,"企業コード" %></br>
    <%= f.search_field :id_eq %>
  </div>
  
  <div class="field">
    <%= f.label :name %></br>
    <%= f.search_field :name_cont %>
  </div>
  
  <div class="field">
    <%= f.label :phone_number %></br>
    <%= f.search_field :phone_number_cont %>
  </div>
  <div class="field">
    <%= f.label :address %></br>
    <%= f.search_field :address_cont %>
  </div>
  
  <div class="field">
    <%= f.label :industry %></br>
    <%= f.search_field :industry_cont %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<br/>
<%= link_to '会社一覧へ戻る', companies_path %>

app/views/companies/show.html.erb
<table class="table  table-bordered table-sm w-50 p-3">
  <tbody>
    <tr>
      <th class="bg-light">会社名</th>
      <td><%= @company.name %></td>
    </tr>
    <tr> 
      <th class="bg-light">TEL</th>
      <td><%= @company.phone_number %></td>
    </tr>
    <tr>
      <th class="bg-light">住所</th> 
      <td><%= @company.address %></td>
    </tr>
    <tr>
      <th class="bg-light">業種</th>
      <td><%= @company.industry %></td>
    </tr>
  </tbody>
</table>

</br>
<%= link_to '案件検索', search_company_matters_path(@company) %>
<div class="table-responsive-sm">
<table class="table table-bordered table-sm">
  <thead class="thead-light">
    <tr>
      <th scope="col"><%= sort_link(@q_matter, :id, "案件コード") %></th>
      <th scope="col"><%= sort_link(@q_matter, :updated_at, "案件更新日") %></th>
      <th scope="col"><%= sort_link(@q_matter, :name , "案件名") %></th>
      <th scope="col"><%= sort_link(@q_matter, :detail , "案件詳細") %></th>
      <th scope="col"><%= sort_link(@q_matter, :contact_person , "担当者") %></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @matters.each do |matter| %>
      <tr>
        <td scope="row"><%= link_to format("%010d",matter.id), company_matter_path(@company, matter) %></td>
        <td><%= matter.updated_at.strftime('%Y/%m/%d') %></td>
        <td><%= matter.name %></td>
        <td><%= matter.detail %></td>
        <td><%= matter.contact_person %></td>
        
        <td><%= link_to '案件編集', edit_company_matter_path(@company, matter) %></td>
        <td><%= link_to '案件削除', company_matter_path(@company, matter), method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<%= paginate @matters %>
<%= link_to '案件一覧', company_matters_path(@company) %>
<%= link_to '案件を追加', new_company_matter_path(@company) %>
<br/>

<%= link_to '会社一覧へ戻る', companies_path %>

app/views/home/index.html.erb
<h1 class="display-1 text-white text-center font-weight-bold" style="text-shadow: 0 0 10px rgba(0,0,0,0.5)">CRM</h1>
<h2 class="text-center" style="color: #ccc">顧客管理ソフト</h2>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="fixed-top mt-5 container">
    <div class="alert <%= bs4_bgcolor_for(key) %> alert-dismissable fade show my-3">
      <%= value %>
      <button class="close" data-dismiss="alert">x</button>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-light d-flex flex-column justify-content-end align-items-end">
  <div class="text-muted small px-3">(C)べる鈴木 CRM by Ruby on Rails & Bootstrap 4</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <%= link_to 'CRM', root_path, class: "navbar-brand" %>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
   <ul class="navbar-nav ml-auto">

     <%  if user_signed_in?  %>
       <li class="nav-item">
         <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
       </li>

     <% else %>
       <li class="nav-item">
         <%= link_to "サインアップ", new_user_registration_path, class: "nav-link" %>
       </li>
       <li class="nav-item">
         <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
       </li>
     <% end %>
   </ul>
 </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRM</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%= render "layouts/header" %>
  <%= render "layouts/flash" %>
  <main>
    <div class="container-fruid h-100 p-2 d-flex flex-column">
      <%= yield %>
    </div>
  </main>
   <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRM</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/flash" %>
    <main class="bg-home d-flex align-items-center w-100 h-100">
      <div class="container">
        <div class="row">
          <div class="col-11 col-lg-5 jumbotron mx-auto mt-4" style="box-shadow: 0 0 5px 5px rgba(0, 0, 0, 0.2)">
            <%= yield %>
          </div>
        </div>
      </div>
    </main>
    <%= render "layouts/footer" %>
  </body>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRM</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/flash" %>
    <main class="bg-home d-flex align-items-center w-100 h-100">
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/logs/_form.html.erb
<%= form_with(model: log, url: [@company, @matter,log], local: true) do |form| %>
  <% if log.errors.any? %>
    <div id="error_explanation" class="alert-danger">
      <h2><%= pluralize(log.errors.count, "error") %> 登録に失敗しました:</h2>

      <ul>
      <% log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :next_approach_date %><br/>
    <%= form.date_field :next_approach_date %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, Log.statuses_i18n.keys.map{|k|[I18n.t("enums.log.status.#{k}"), k]} %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>
  
    <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/logs/edit.html.erb
<h1>ログを編集</h1>

<%= render 'form', log: @log %>

<%= link_to '案件詳細に戻る', company_matter_path(id: @log.matter.id) %>

app/views/logs/new.html.erb
<h1>ログを追加</h1>

<%= render 'form', log: @log %>

<%= link_to '案件詳細に戻る', company_matter_path(id: @log.matter.id) %>

app/views/matters/_form.html.erb
<%= form_with(model: matter, url: [@company, matter], local: true) do |form| %>
  <% if matter.errors.any? %>
    <div id="error_explanation" class="alert-danger">
      <h2><%= pluralize(matter.errors.count, "error") %> 登録に失敗しました:</h2>

      <ul>
      <% matter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :detail %>
    <%= form.text_field :detail %>
  </div>

  <div class="field">
    <%= form.label :contact_person %>
    <%= form.text_field :contact_person %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/matters/edit.html.erb
<h1>案件を編集</h1>

<%= render 'form', matter: @matter %>

<%= link_to '会社詳細に戻る', company_path(id: @company.id) %>

app/views/matters/index.html.erb
<h1>案件一覧</h1>
<table  class="table table-bordered table-sm">
  <thead  class="thead-light">
    <tr>
      <th scope="col"><%= sort_link(@q_matter, :id, "案件コード") %></th>
      <th scope="col"><%= sort_link(@q_matter, :updated_at, "案件更新日") %></th>
      <th scope="col"><%= sort_link(@q_matter, :name , "案件名") %></th>
      <th scope="col"><%= sort_link(@q_matter, :detail , "案件詳細") %></th>
      <th scope="col"><%= sort_link(@q_matter, :contact_person , "担当者") %></th>
    </tr>
  </thead>

  <tbody>
    <% @matters.each do |matter| %>
      <tr>
        <td><%= link_to format("%010d",matter.id), company_matter_path(@company, matter) %></td>
        <td><%= matter.updated_at.strftime('%Y/%m/%d') %></td>
        <td><%= matter.name %></td>
        <td><%= matter.detail %></td>
        <td><%= matter.contact_person %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @matters %>
<%= link_to '案件を追加', new_company_matter_path(@company) %>
<br/>
<%= link_to '会社詳細へ戻る', company_path(@company) %>

app/views/matters/new.html.erb
<h1>案件を追加</h1>

<%= render 'form', matter: @matter %>

<%= link_to '会社詳細に戻る', company_path(id: @company.id) %>

app/views/matters/search.html.erb
<h2>検索フォーム</h2>
<%= search_form_for @q_matter, url:company_matters_path  do |f| %>

  <div class="field">
    <%= f.label :id ,"案件コード" %></br>
    <%= f.search_field :id_eq %>
  </div>
  
  <div class="field">
    <%= f.label :name %></br>
    <%= f.search_field :name_cont %>
  </div>
  <div class="field">
    <%= f.label :detail %></br>
    <%= f.search_field :detail_cont %>
  </div>
  
  <div class="field">
    <%= f.label :contact_person %></br>
    <%= f.search_field :contact_person_cont %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<br/>
<%= link_to '会社詳細へ戻る', company_path(@company) %>

app/views/matters/show.html.erb
<table class="table  table-bordered table-sm w-50 p-3">
  <tbody>
    <tr>
      <th class="bg-light">案件名</th>
      <td><%= @matter.name %></td>
    </tr>
    <tr> 
      <th class="bg-light">案件詳細</th>
      <td><%= @matter.detail %></td>
    </tr>
    <tr>
      <th class="bg-light">担当者</th> 
      <td><%= @matter.contact_person %></td>
    </tr>
  </tbody>
</table>

<h2>ログ</h2>
<div class="table-responsive-sm">
<table class="table table-bordered table-sm">
  <thead class="thead-light">
    <tr>
      <th scope="col"><%= sort_link(@q_log, :updated_at, "ログ更新日") %></th>
      <th scope="col"><%= sort_link(@q_log, :next_approach_date, "次回アプローチ日") %></th>
      <th scope="col"><%= sort_link(@q_log, :status, "ステータス") %></th>
      <th scope="col"><%= sort_link(@q_log, :comment, "コメント") %></th>
      <th scope="col"><%= sort_link(@q_log, :user_id, "対応者") %></th>
      <th colspan="2"></th>
    </tr>
  </thead>

 <tbody>
    <% @logs.each do |log| %>
      <tr>
        <td scope="row"><%= log.updated_at.strftime('%Y/%m/%d %H:%M') %></td>
        <td><%= log.next_approach_date.strftime('%Y/%m/%d') %></td>
        <td><%= log.status_i18n %></td>
        <td><%= log.comment %></td>
        <td><%= User.find_by(id: log.user_id).name %></td>
        <% if current_user.id == log.user_id  %>
        <td><%= link_to 'ログ編集', edit_company_matter_log_path(log.matter.company,log.matter, log) %></td>
        <td><%= link_to 'ログ削除', company_matter_log_path(log.matter.company,log.matter, log), method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
        <% else  %>
        <td colspan="2"></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<%= paginate @logs %>
<%= link_to 'ログを追加', new_company_matter_log_path(@company,@matter) %>
</br>
<p><%= link_to '企業情報に戻る', company_path(@company) %></p>